name: PlanB
main: planb\PlanB
version: 1.5.2
api: [3.0.0, 4.0.0]
load: POSTWORLD
author: Gamecrafter
description: Hackers can't cripple your server anymore!
permissions:
 planb:
  default: true
  children:
   planb.command:
    default: true
    children:
     planb.command.planb:
      default: true
